server:
  port: 8080

spring:
  application:
    name: movie

eureka:
  instance:
    appname: movie
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://Admin:admin123@localhost:3000/eureka/