spring:
  datasource:
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: sa
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

